Fail sim 1.1.3 internal
os-fpga/FPGA_PRIMITIVES_MODELS pull request #40
Opened 2024-04-04 05:09 UTC by moinijaz

- Synthesis attribute (* iopad_external_pin *) added for **I_BUF_DS**, **O_BUF_DS** and **O_BUFT_DS**.

2024-04-04 05:13 UTC, NadeemYaseen approved these changes

2024-04-04 10:12 UTC, ashrafnisar commented on blackbox_models/cell_sim_blackbox.v
> +  (* iopad_external_pin *)
Why do we have external pin attribute on the Enable pin? This pin will always be driven from the fabric.

2024-04-04 10:16 UTC, ashrafnisar requested changes
The EN pin has an attribute for external pin. That needs to be corrected.

2024-04-04 10:21 UTC, AYYAZmayo commented on blackbox_models/cell_sim_blackbox.v
> +  (* iopad_external_pin *)
@ashrafnisar , it means I_BUF will not inserted on this enable pin.

2024-04-04 18:35 UTC, alaindargelas commented on blackbox_models/cell_sim_blackbox.v
> +  (* iopad_external_pin *)
This pin *cannot* be driven physically as a top design port (Device PAD), unless there is an I_BUF and a WireLUT that connects it to a device PAD. So the attribute is incorrect on that enable pin. @ashrafnisar please confirm

2024-04-05 11:01 UTC, AYYAZmayo commented on blackbox_models/cell_sim_blackbox.v
> +  (* iopad_external_pin *)
@alaindargelas , after discussion with @ashrafnisar it is decided not to put (* iopad_external_pin *) on **En** pin. So I think we need to correct this fix.

2024-04-05 17:20 UTC, alaindargelas commented
Closing this PR as partially incorrect.

2024-04-05 22:19 UTC, alaindargelas commented
Still merge this change. New new release 1.1.5 will address sub issue.

2024-04-05 22:20 UTC, merged